# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormAddEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAddEmployee(object):
    def setupUi(self, FormAddEmployee):
        FormAddEmployee.setObjectName("FormAddEmployee")
        FormAddEmployee.resize(400, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormAddEmployee)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblEmployeeName = QtWidgets.QLabel(FormAddEmployee)
        self.lblEmployeeName.setObjectName("lblEmployeeName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblEmployeeName)
        self.lineEmployeeName = QtWidgets.QLineEdit(FormAddEmployee)
        self.lineEmployeeName.setObjectName("lineEmployeeName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEmployeeName)
        self.lblEmployeePosition = QtWidgets.QLabel(FormAddEmployee)
        self.lblEmployeePosition.setObjectName("lblEmployeePosition")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEmployeePosition)
        self.cmbEmployeePosition = QtWidgets.QComboBox(FormAddEmployee)
        self.cmbEmployeePosition.setObjectName("cmbEmployeePosition")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbEmployeePosition)
        self.lblEmployeeJoinDate = QtWidgets.QLabel(FormAddEmployee)
        self.lblEmployeeJoinDate.setObjectName("lblEmployeeJoinDate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblEmployeeJoinDate)
        self.dteEmployeeJoinDate = QtWidgets.QDateTimeEdit(FormAddEmployee)
        self.dteEmployeeJoinDate.setObjectName("dteEmployeeJoinDate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dteEmployeeJoinDate)
        self.lblEmployeeSalary = QtWidgets.QLabel(FormAddEmployee)
        self.lblEmployeeSalary.setObjectName("lblEmployeeSalary")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblEmployeeSalary)
        self.spinEmployeeSalary = QtWidgets.QDoubleSpinBox(FormAddEmployee)
        self.spinEmployeeSalary.setObjectName("spinEmployeeSalary")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinEmployeeSalary)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayoutAddStudent = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAddStudent.setObjectName("horizontalLayoutAddStudent")
        self.btnSaveEmployee = QtWidgets.QPushButton(FormAddEmployee)
        self.btnSaveEmployee.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnSaveEmployee.setObjectName("btnSaveEmployee")
        self.horizontalLayoutAddStudent.addWidget(self.btnSaveEmployee)
        self.btnClearEmployee = QtWidgets.QPushButton(FormAddEmployee)
        self.btnClearEmployee.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnClearEmployee.setObjectName("btnClearEmployee")
        self.horizontalLayoutAddStudent.addWidget(self.btnClearEmployee)
        self.btnCancelEmployee = QtWidgets.QPushButton(FormAddEmployee)
        self.btnCancelEmployee.setObjectName("btnCancelEmployee")
        self.horizontalLayoutAddStudent.addWidget(self.btnCancelEmployee)
        self.verticalLayout.addLayout(self.horizontalLayoutAddStudent)

        self.retranslateUi(FormAddEmployee)
        QtCore.QMetaObject.connectSlotsByName(FormAddEmployee)

    def retranslateUi(self, FormAddEmployee):
        _translate = QtCore.QCoreApplication.translate
        FormAddEmployee.setWindowTitle(_translate("FormAddEmployee", "Add Employee"))
        self.lblEmployeeName.setText(_translate("FormAddEmployee", "Employee Name"))
        self.lblEmployeePosition.setText(_translate("FormAddEmployee", "Employee Role"))
        self.lblEmployeeJoinDate.setText(_translate("FormAddEmployee", "Employee Join Date"))
        self.dteEmployeeJoinDate.setDisplayFormat(_translate("FormAddEmployee", "dd/mm/yy"))
        self.lblEmployeeSalary.setText(_translate("FormAddEmployee", "Employee Salary"))
        self.btnSaveEmployee.setText(_translate("FormAddEmployee", "Save"))
        self.btnClearEmployee.setText(_translate("FormAddEmployee", "Clear"))
        self.btnCancelEmployee.setText(_translate("FormAddEmployee", "Cancel"))
