# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormEditDeleteEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormEditDeleteEmployee(object):
    def setupUi(self, FormEditDeleteEmployee):
        FormEditDeleteEmployee.setObjectName("FormEditDeleteEmployee")
        FormEditDeleteEmployee.resize(376, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormEditDeleteEmployee)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblEditEmployeeID = QtWidgets.QLabel(FormEditDeleteEmployee)
        self.lblEditEmployeeID.setObjectName("lblEditEmployeeID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblEditEmployeeID)
        self.lineEditEmployeeID = QtWidgets.QLineEdit(FormEditDeleteEmployee)
        self.lineEditEmployeeID.setEnabled(False)
        self.lineEditEmployeeID.setObjectName("lineEditEmployeeID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditEmployeeID)
        self.lblEditEmployeeDate = QtWidgets.QLabel(FormEditDeleteEmployee)
        self.lblEditEmployeeDate.setObjectName("lblEditEmployeeDate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblEditEmployeeDate)
        self.lblEditEmployeePosition = QtWidgets.QLabel(FormEditDeleteEmployee)
        self.lblEditEmployeePosition.setObjectName("lblEditEmployeePosition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblEditEmployeePosition)
        self.cmbEditEmployeePosition = QtWidgets.QComboBox(FormEditDeleteEmployee)
        self.cmbEditEmployeePosition.setObjectName("cmbEditEmployeePosition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbEditEmployeePosition)
        self.dteEditEmployeeDate = QtWidgets.QDateEdit(FormEditDeleteEmployee)
        self.dteEditEmployeeDate.setObjectName("dteEditEmployeeDate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dteEditEmployeeDate)
        self.lblEmployeeName = QtWidgets.QLabel(FormEditDeleteEmployee)
        self.lblEmployeeName.setObjectName("lblEmployeeName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEmployeeName)
        self.lineEditEmployeeName = QtWidgets.QLineEdit(FormEditDeleteEmployee)
        self.lineEditEmployeeName.setObjectName("lineEditEmployeeName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditEmployeeName)
        self.lblEditEmployeeSalary = QtWidgets.QLabel(FormEditDeleteEmployee)
        self.lblEditEmployeeSalary.setObjectName("lblEditEmployeeSalary")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblEditEmployeeSalary)
        self.spinEditEmployeeSalary = QtWidgets.QSpinBox(FormEditDeleteEmployee)
        self.spinEditEmployeeSalary.setObjectName("spinEditEmployeeSalary")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinEditEmployeeSalary)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEditEmployeePrevious = QtWidgets.QPushButton(FormEditDeleteEmployee)
        self.btnEditEmployeePrevious.setObjectName("btnEditEmployeePrevious")
        self.horizontalLayout.addWidget(self.btnEditEmployeePrevious)
        self.btnEditEmployeeNext = QtWidgets.QPushButton(FormEditDeleteEmployee)
        self.btnEditEmployeeNext.setObjectName("btnEditEmployeeNext")
        self.horizontalLayout.addWidget(self.btnEditEmployeeNext)
        self.btnEditEmployeeSave = QtWidgets.QPushButton(FormEditDeleteEmployee)
        self.btnEditEmployeeSave.setObjectName("btnEditEmployeeSave")
        self.horizontalLayout.addWidget(self.btnEditEmployeeSave)
        self.btnEditEmployeeDelete = QtWidgets.QPushButton(FormEditDeleteEmployee)
        self.btnEditEmployeeDelete.setObjectName("btnEditEmployeeDelete")
        self.horizontalLayout.addWidget(self.btnEditEmployeeDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FormEditDeleteEmployee)
        QtCore.QMetaObject.connectSlotsByName(FormEditDeleteEmployee)

    def retranslateUi(self, FormEditDeleteEmployee):
        _translate = QtCore.QCoreApplication.translate
        FormEditDeleteEmployee.setWindowTitle(_translate("FormEditDeleteEmployee", "Edit / Delete Employee"))
        self.lblEditEmployeeID.setText(_translate("FormEditDeleteEmployee", "Employee ID"))
        self.lblEditEmployeeDate.setText(_translate("FormEditDeleteEmployee", "Employee Join Date"))
        self.lblEditEmployeePosition.setText(_translate("FormEditDeleteEmployee", "Employee Role"))
        self.lblEmployeeName.setText(_translate("FormEditDeleteEmployee", "Employee Name"))
        self.lblEditEmployeeSalary.setText(_translate("FormEditDeleteEmployee", "Employee Salary"))
        self.btnEditEmployeePrevious.setText(_translate("FormEditDeleteEmployee", "Previous"))
        self.btnEditEmployeeNext.setText(_translate("FormEditDeleteEmployee", "Next"))
        self.btnEditEmployeeSave.setText(_translate("FormEditDeleteEmployee", "Update"))
        self.btnEditEmployeeDelete.setText(_translate("FormEditDeleteEmployee", "Delete"))
