# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormEditDeleteStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormEditDeleteStudent(object):
    def setupUi(self, FormEditDeleteStudent):
        FormEditDeleteStudent.setObjectName("FormEditDeleteStudent")
        FormEditDeleteStudent.resize(369, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormEditDeleteStudent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblStudentID = QtWidgets.QLabel(FormEditDeleteStudent)
        self.lblStudentID.setObjectName("lblStudentID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStudentID)
        self.lineEditStudentID = QtWidgets.QLineEdit(FormEditDeleteStudent)
        self.lineEditStudentID.setEnabled(False)
        self.lineEditStudentID.setText("")
        self.lineEditStudentID.setObjectName("lineEditStudentID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditStudentID)
        self.lblEditStudentName = QtWidgets.QLabel(FormEditDeleteStudent)
        self.lblEditStudentName.setObjectName("lblEditStudentName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEditStudentName)
        self.lineEditStudentName = QtWidgets.QLineEdit(FormEditDeleteStudent)
        self.lineEditStudentName.setObjectName("lineEditStudentName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditStudentName)
        self.lblEditStudentGrade = QtWidgets.QLabel(FormEditDeleteStudent)
        self.lblEditStudentGrade.setObjectName("lblEditStudentGrade")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblEditStudentGrade)
        self.lineEditStudentGrade = QtWidgets.QLineEdit(FormEditDeleteStudent)
        self.lineEditStudentGrade.setObjectName("lineEditStudentGrade")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditStudentGrade)
        self.lblEditStudentAge = QtWidgets.QLabel(FormEditDeleteStudent)
        self.lblEditStudentAge.setObjectName("lblEditStudentAge")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblEditStudentAge)
        self.lineEditStudentAge = QtWidgets.QLineEdit(FormEditDeleteStudent)
        self.lineEditStudentAge.setObjectName("lineEditStudentAge")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditStudentAge)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEditStudentPrevious = QtWidgets.QPushButton(FormEditDeleteStudent)
        self.btnEditStudentPrevious.setObjectName("btnEditStudentPrevious")
        self.horizontalLayout.addWidget(self.btnEditStudentPrevious)
        self.btnEditStudentNext = QtWidgets.QPushButton(FormEditDeleteStudent)
        self.btnEditStudentNext.setObjectName("btnEditStudentNext")
        self.horizontalLayout.addWidget(self.btnEditStudentNext)
        self.btnEditStudentSave = QtWidgets.QPushButton(FormEditDeleteStudent)
        self.btnEditStudentSave.setObjectName("btnEditStudentSave")
        self.horizontalLayout.addWidget(self.btnEditStudentSave)
        self.btnEditStudentDelete = QtWidgets.QPushButton(FormEditDeleteStudent)
        self.btnEditStudentDelete.setObjectName("btnEditStudentDelete")
        self.horizontalLayout.addWidget(self.btnEditStudentDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FormEditDeleteStudent)
        QtCore.QMetaObject.connectSlotsByName(FormEditDeleteStudent)

    def retranslateUi(self, FormEditDeleteStudent):
        _translate = QtCore.QCoreApplication.translate
        FormEditDeleteStudent.setWindowTitle(_translate("FormEditDeleteStudent", "Edit / Delete Student"))
        self.lblStudentID.setText(_translate("FormEditDeleteStudent", "Student ID"))
        self.lblEditStudentName.setText(_translate("FormEditDeleteStudent", "Name"))
        self.lblEditStudentGrade.setText(_translate("FormEditDeleteStudent", "Grade"))
        self.lblEditStudentAge.setText(_translate("FormEditDeleteStudent", "Age"))
        self.btnEditStudentPrevious.setText(_translate("FormEditDeleteStudent", "Previous"))
        self.btnEditStudentNext.setText(_translate("FormEditDeleteStudent", "Next"))
        self.btnEditStudentSave.setText(_translate("FormEditDeleteStudent", "Update"))
        self.btnEditStudentDelete.setText(_translate("FormEditDeleteStudent", "Delete"))
