# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogAlert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(228, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblDialogAlert = QtWidgets.QLabel(Dialog)
        self.lblDialogAlert.setObjectName("lblDialogAlert")
        self.verticalLayout.addWidget(self.lblDialogAlert)
        self.dlgBtnYesNo = QtWidgets.QDialogButtonBox(Dialog)
        self.dlgBtnYesNo.setOrientation(QtCore.Qt.Horizontal)
        self.dlgBtnYesNo.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.dlgBtnYesNo.setCenterButtons(True)
        self.dlgBtnYesNo.setObjectName("dlgBtnYesNo")
        self.verticalLayout.addWidget(self.dlgBtnYesNo)

        self.retranslateUi(Dialog)
        self.dlgBtnYesNo.accepted.connect(Dialog.accept)
        self.dlgBtnYesNo.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblDialogAlert.setText(_translate("Dialog", "Are you sure you wish to delete *****?"))
